version: "2.1"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "4040:4040"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"